- ignore: {name: "Monoid law, left identity", within: [Profunctor.Coexp.Test, Fold.Test, Monoid.Fork.Test]}
- ignore: {name: "Monoid law, right identity", within: [Profunctor.Coexp.Test, Fold.Test, Monoid.Fork.Test]}
- ignore: {name: "Evaluate", within: Iso.Test}
