name: Haskell CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.10", "9.0", "9.2"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - uses: haskell/actions/setup@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}

    - uses: actions/cache@v2
      name: Cache ~/.cabal/packages
      with:
        path: ~/.cabal/packages
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages
    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store
    - uses: actions/cache@v2
      name: Cache dist-newstyle
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-repo-dist

    - name: Install dependencies
      run: |
        cabal v2-update
        cabal v2-configure --project-file=cabal.project.ci --enable-benchmarks --enable-tests --write-ghc-environment-files=always -j2
        cabal v2-build     --project-file=cabal.project.ci --only-dependencies all

    - name: Build & test
      run: |
        cabal v2-build   --project-file=cabal.project.ci all
        cabal v2-run     --project-file=cabal.project.ci fresnel:test
        cabal v2-haddock --project-file=cabal.project.ci all
        cabal v2-sdist   --project-file=cabal.project.ci all
        cd fresnel && cabal check ; cd ..
        cd fresnel-diagram && cabal check ; cd ..
